---
title: "ENS 623 - Spring 2020 - Problem Set 5"
output: html_document
---

**Please submit this homework as an R Markdown (Rmd) file AND a Word file (docx).**
See the introduction to [Problem Set 1](http://mlammens.github.io/ENS-623-Research-Stats/problem_sets/Problem-set-1.html) if you need more information about the Rmd format.

#### File name

Your file should use the following naming scheme

**`[last name]_ENS623_SP20_PS5.Rmd`**

For example, 

`Lammens_ENS623_SP20_PS5.Rmd`


## Working with the multinomial distribution

Near the end of class on Wednesday, I introduced the [multinomial distribution](https://en.wikipedia.org/wiki/Multinomial_distribution).
Using this distribution, you can calculate the exact probability of getting *your bag of M&Ms*. 
To do this, you need to know the probability of getting each color.
In class, we used probability values reported by the Mars company as recently as 2008. 
This [article](https://qz.com/918008/the-color-distribution-of-mms-as-determined-by-a-phd-in-statistics/) includes these numbers, but also updated numbers from two different M&M factories.

**For this problem set, calcualte the probability of getting your bag of M&Ms using (15 points):**

1. The 2008 probabilities (similar to what we used in class).
2. The 2017, New Jersey Factory probabilities.
3. The 2017, Tennessee Factory probabilities.

**Please do all calculations in R.**

**Based on the probabilities calculated above, write an argument about where your bag most likely came from (10 points).**