---
title: "ENS 623 - Spring 2019 - Problem Set 5"
output: html_document
---

**Please submit this homework as an R Markdown (Rmd) file.**
See the introduction to [Problem Set 1](http://mlammens.github.io/ENS-623-Research-Stats/problem_sets/Problem-set-1.html) if you need more information about the Rmd format.

#### File name

Your file should use the following naming scheme

**`[last name]_ENS623_SP19_PS5.Rmd`**

For example, 

`Lammens_ENS623_SP19_PS5.Rmd`

#### Grading note

* Problem 1 is worth 15 points
* Problem 2 is worth 5 points
* Problem 3 is worth 5 points

# Overview

In this problem set, you are going to work on comparing groups of data **using ANOVA**, to see if there are significant differences between groups.
We will be using data on Phosphorus levels in the soil at Pace University.
In this problem set, you will be testing for whether there is a difference between **sites**.

First, let's get the data.


```{r soil_data}
soil_data <- read.csv("https://www.dropbox.com/s/b8vanatf6kejuba/soil_p_data.csv?dl=1")
summary(soil_data)
```

# Problem 1 - ANOVA by hand

Calculate all of the components to perform an ANOVA and build your ANOVA table.
You might want to consult the [OpenIntro supplementary chatper on ANOVA](https://www.openintro.org/download.php?file=stat_extra_anova_calculations&referrer=/stat/textbook.php) for help.

**Show all of your R code and use #s to add comments to keep track of your calculations.**


Determine if we reject or accept our null hypothesis, where $H_0$ = there is no difference in phosphorus levels at the different sites.

**Provide a full written answer.**


# Problem 2 - ANOVA with R

Use either `summary(aov())` or `anova(lm())` to perform an ANOVA identical to what you did "by hand" above.

**Show all of your R code.**



# Problem 3 - Tukey's Honest Significant Differences test

Use `TukeyHSD()` to perform all multiple comparisons, and to determine with sites are different from each other.

**Show all of your R code.**

Which, if any, sites do you think are different from one another?

**Provide a full written answer.**
