---
title: "ENS 623 - Spring 2020 - Problem Set 1"
output: html_document
---

**Please submit this homework on Blackboard as *both* an R Markdown (Rmd) and DOCX file.**

As I mentioned during our first meeting, rmarkdown is a way to incorporate text, with simple formatting, with R code chunks.
Rather than spell out how to create an Rmd file here, I recommend you consult the following resources:

* [RStudio Rmarkdown Quick Tour](http://rmarkdown.rstudio.com/authoring_quick_tour.html)
* [RStudio Rmarkdown Intro Article](http://rmarkdown.rstudio.com/articles_intro.html)
* [OurCodingClub Intro Example](https://ourcodingclub.github.io/2016/11/24/rmarkdown-1.html)

#### Your file should use the following naming scheme

**`[last name]_ENS623_SP20_PS1.Rmd`**

For example, 

`Lammens_ENS623_SP20_PS1.Rmd`

#### Grading note

* Part 1 is worth 10 points
* Part 2 is worth 15 points

# Part 1 - Introducing the Iris data set

In class I mentioned that the R package `datasets` includes several different kinds of data sets to use in R. In this problem set, we'll work with the `iris` data set. Using any of the help functions we learned in class, `?` or `help.search`, find the help page for the iris data set. 

* Briefly describe what these data are.
* Think about a model that might describe the varition in petal length values in this data set.


# Part 2 - Play with the the `iris` data set

Use the `head`, `tail`, and `summary` functions to investigate the `iris` data set. Use the help functions (or search online) to figure out *how* to use these functions and *what* these functions return. Make at least three observations about the data and/or the data set using these functions.






