---
title: "ENS 623 - Spring 2020 - Problem Set 11"
output: html_document
---

**Please submit this homework as an R Markdown (Rmd) file AND a Word file (docx).**
See the introduction to [Problem Set 1](http://mlammens.github.io/ENS-623-Research-Stats/problem_sets/Problem-set-1.html) if you need more information about the Rmd format.

#### File name

Your file should use the following naming scheme

**`[last name]_ENS623_SP20_PS11.Rmd`**

For example, 

`Lammens_ENS623_SP20_PS11.Rmd`


# Overview

The dataset loaded in to R in the code below reports on the success (as assessed by the column `Scent`) of luring spruce moths using different baits (`Bait`) placed at varying heights (`Location`) within a forest canopy.

```{r}
moth <- read.csv(file = "https://mlammens.github.io/ENS-623-Research-Stats/data/spruce_moth_traps.csv")
```

# Two-way ANOVA "by hand" (15 points) 

Write an R script to calculate the 2-way ANOVA table (including interactions) manually (i.e. calculating all the entries including the F and p-values). 
Assume that Baits and Location are fixed (not random).
(**Hint:** To complete this problem, calculate the results for the equations described in **Table 9.8 in Quinn and Keough** and F-ratios as described in **Table 12.1 in Logan**.)

# Two-way ANOVA by function (10 points)

Use the `anova` and `lm` (or `aov`) functions to analyze Scent as a function of Location and Bait. 

* How should the intercept be interpreted? 
* What determines what R uses as the model intercept?
* Compare your ANOVA table from **Part 1** against that produced by the R functions. Do you get the same answer as you calculated by hand?
